[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "devenv-polyglot"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
base = [ # always-installed by devenv
  "pytest",
  "restate-sdk",
  "invoke",
  "python-dateutil",
  "watchfiles",
  "pytest-cov",
  "pytest-mock",
  "opendal",
  "plumbum",
  "loguru",
  # "polyfactory",
  "rich",
  "orjson",
  "minijinja",
  "pydantic",
  "tabulate",
  "typer",
  "httpx",
  "pydantic-settings", # replaces python-dotenv
  # "websockets",
  # "pathvalidate",
  # "pathspec",
  # "s3fs",
  "universal-pathlib",
  # "fsspec[s3,http]",
  "icecream",
  # "libsql" # replaces "aiosqlite",
  #  "uvloop",
  #  "python-magic",
  #  "aiofiles",
]

tui = ["textual",
]

fastapi = [
  "fastapi",
# minijinja replaced "jinja2-fragments", "fastapi-htmx","fasthx[jinja]",
  "granian[pname,uvloop,reload]",
  "asyncpg",                               # Already have it - use for caching too
  "structlog",
  "python-multipart",
  "connect-python", # for buf/connectrpc
  "opentelemetry-instrumentation-fastapi",
  "opentelemetry-exporter-otlp",
  "prometheus-client",
  "libsql", # this is turso
  # "supabase",
  "slowapi",
  "fastapi-cache2",
  "fastapi-pagination",
  "pytailwindcss",
]
marimo = [
  "marimo",
  "ibis-framework[duckdb]",
  "openai",
  "python-lsp-server",
  # "d2-widget",
  # "pygwalker",
  # "polars",
  "numpy",
  "dlt",
  "altair",
  "vegafusion",
  "vl-convert-python",
  "pandera[ibis]",
  # "bambi",
  "joblib",
]
daft = ["daft[google, iceberg, postgres, ray, sql, audio, viz]"]

adbc = [
"adbc-driver-postgresql",
"adbc-driver-duckdb",
"pyarrow",]

dagster = [
  "dagster",
  "data-diff",
  "sqlmesh[duckdb,github]",
  "dagster-duckdb",
  # "whylogs",
  # "apache-gravitino",
  "dagster-postgres",
  "dagster-polars",
  "dagster-sqlmesh",
  "dagster-dlt",
  "dagster-ducklake",
  "dagster-iceberg",
  "dagster-ibis",
  "dagster-pandera",
  "dagster-dg-cli",
  "dagster-webserver",
]
cloud = [
"pytest-kubernetes",
"kr8s",
"infisicalsdk",
]

[tool.dg]
directory_type = "project"
root_module = "pipeline"   # Must match your src/ folder name


[tool.hatch.build.targets.wheel]
packages = ["src/devenv_polyglot"]
