[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "devenv-polyglot"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
base = [               # always-installed by devenv
    "pytest",
    "python-dateutil",
    # "pytest-cov",
    "pytest-mock",
    "loguru",
    # "polyfactory",
    # "rich",
    "orjson",
    "pydantic",
    "tabulate",
    "toolz",
    "typer",
    "httpx",
    "pydantic-settings", # replaces python-dotenv
    "websockets",
    "certifi",
    "pathvalidate",
    "pathspec",
  #  "uvloop",
  #  "python-magic",
  #  "aiofiles",
    "anyio",
   # "aiosqlite",
    ]
fastapi = [
    "fastapi[all]",
    "fastapi-htmx",
    "uvicorn[standard]",
    "asyncpg",                   # Already have it - use for caching too
    "python-multipart",
    "opentelemetry-instrumentation-fastapi",
    "opentelemetry-exporter-otlp",
    "prometheus-client",
    "supabase",
    "slowapi",
    "fastapi-cache2",
    "fastapi-pagination",
]
marimo = [
    "marimo",
    "duckdb",
    "ibis-framework[duckdb]",
    "openai",
    # "pandas",
    "python-lsp-server",
    "d2-widget",
    # "pygwalker",
    "connectorx",
    "polars",
    # "pyarrow",
    "numpy",
    "altair",
    "vegafusion",
    "vl-convert-python",
    "pandera",
    # "bambi",
    "joblib",
    ]
daft = [
    "daft[google, iceberg, postgres, ray, sql, audio, viz]",
    ]
dagster = [
    "dagster",
    "data-diff",
    "sqlmesh[duckdb,github,iceberg]",
    "dlt[filesystem,parquet,s3,cli,duckdb,http,iceberg]",
    "dagster-duckdb",
    # "whylogs",
    "dagster-postgres",
    "dagster-polars",
    "dagster-sqlmesh",
    "dagster-dlt",
    "dagster-ducklake",
    "dagster-iceberg",
    "dagster-ibis",
    "dagster-pandera",
    "dagster-dg-cli",
    "dagster-webserver",
]

[tool.dg]
directory_type = "project"
root_module = "pipeline"  # Must match your src/ folder name
